image: win7

default:
  prepare:
    exec:
    - node -v
    - npm -v
    - npm install -g tnpm --registry=http://registry.npm.alibaba-inc.com
    - tnpm -v
    - tnpm install --unsafe-perm
  unit_test:
    exec:
    - tnpm run ie
    - tnpm run chrome

    plugin:
    - name: encode
      param:
        type: utf-8
